### ISSUE TITLE
Problem with knot_exporter output

### ISSUE THREAD

**Issue by leahoswald** [ghedo/knot_exporter#1]
I try to run your knot_exporter together with a knot installation in version 2.6.7. But if I query the exporter I only get the following very limited output and it takes a lot of time (30sec) to get this small response:

```
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="4",patchlevel="8",version="3.4.8"} 1.0
# HELP knot_server_zone_count 
# TYPE knot_server_zone_count gauge
knot_server_zone_count 5559.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 275542016.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 46186496.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1531235542.82
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 262.02000000000004
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 8.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0
```
In the terminal running the exporter with an additional `print(zone_stats)` in [line 433](https://github.com/ghedo/knot_exporter/blob/master/knot_exporter#L433) I get a really big data dump so there is data that should be displayed.

Is there any problem you can imagine that could lead to such a behavior?

**Comment by ghedo** [comment]
The long time it takes to run is likely due to the amount of data it needs to process, and the fact that the script is not particularly well optimized.

I _think_ the reason why it is reporting very few metrics is that they most of them have value zero, so [this condition](https://github.com/ghedo/knot_exporter/blob/master/knot_exporter#L438)  becomes true and the metric is skipped. The reason for this behavior IIRC was to avoid having to fetch and store a whole bunch of metrics that are all zero.

If you remove that if, does it report all the metrics? Also, are the counters reported by knot actually zero? If not there might be a bug in the script that makes it think the metrics are zero.

**Comment by leahoswald** [comment]
Removing the line helped to debug it and yes there are metrics but all with zero values :) Also I now better understand how the statistic module of knot works. So I think this question is solved and thanks for helping :)
